version: '3.7'

services:
  repro:
    container_name: repro
    build:
      context: .
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    command: >
      bash -c "sleep infinity"
